/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyDiemSinhVienHAUI.Xem;

import QuanLyDiemSinhVienHAUI.DangNhap.Dangnhap;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author Tuan Bao
 */
public class xemketquathi extends javax.swing.JFrame {

    Connectionxem db = new Connectionxem();
    private ArrayList<ketquathi> dsdiem = new ArrayList<ketquathi>();
    ketquathi diems = new ketquathi();
    /**
     * Creates new form xemketquathi
     */
    public xemketquathi() {
        initComponents();
        setLocation(500,150);
        hienthidiem();
        loadTable();
    }
    public void loadTable(){
       jtbketquathi.setModel(new CustomTablediemthi(dsdiem));
    }
      public ArrayList<ketquathi> hienthidiem(){
        ketquathi tb = getdiemdetal();
        dsdiem = getdsvt(db.getdiemthi(tb));
        return dsdiem;
       
    }
    private ketquathi getdiemdetal() {
        Dangnhap dn = new Dangnhap();
        String masv = dn.tkmasv;
        
        return new ketquathi(masv,null,null,null,null,null,null,null,null,null,null,null,null);
    }
    public ArrayList<ketquathi> getdsvt(ResultSet rs) {
        ArrayList<ketquathi> items = new ArrayList<ketquathi>();
        
        try{
            while(rs.next()){
                ketquathi item = new ketquathi();
                item.setMaSinhVien(rs.getString(1));
                item.setHoten(rs.getString(2));
                item.setHocky(rs.getString(3));
                item.setMaMon(rs.getString(4));
                item.setTenmon(rs.getString(5));
                item.setDiemtb(rs.getDouble(7));
                
                item.setSotc(rs.getDouble(6));
                if(rs.getString(13).equals("Học lại"))
                {
                    item.setDiemthi(null);
                    item.setDiemtk10(null);
                    item.setDiemtk4(null);
                    item.setDiemchu("F");
                    item.setXeploai("Kém");
                }
                else {
                    if(rs.getDouble(8)==0){
                        item.setDiemthi(null);
                        item.setDiemtk10(null);
                        item.setDiemtk4(null);
                    }
                    else{
                        item.setDiemthi(rs.getDouble(8));
                        item.setDiemtk10(rs.getDouble(9));
                        item.setDiemtk4(rs.getDouble(10));
                    }
                    
                    item.setDiemchu(rs.getString(11));
                    item.setXeploai(rs.getString(12));
                }
//                item.setDiemchu(rs.getString(11));
//                item.setXeploai(rs.getString(12));
                items.add(item);
                txtmasinhvien.setText(rs.getString(1));
                txthoten.setText(rs.getString(2));
            }
            
        }
        catch(SQLException ex){
            
        }
        return items;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtmasinhvien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbketquathi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kết quả thi");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Kết quả thi các môn");

        jButton1.setIcon(new javax.swing.ImageIcon("E:\\dowload\\JavaApplication2\\JavaApplication2\\src\\anh\\back.png")); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel3.setText("Họ và tên sinh viên");

        jLabel2.setText("Mã sinh viên");

        jtbketquathi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbketquathi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(213, 213, 213)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txthoten, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(txtmasinhvien))))
                        .addGap(0, 361, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jButton1))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmasinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        sinhvien sv = new sinhvien();
        sv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(xemketquathi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(xemketquathi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(xemketquathi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(xemketquathi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dangnhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbketquathi;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtmasinhvien;
    // End of variables declaration//GEN-END:variables
}
