/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyDiemSinhVienHAUI.DangNhap;

import QuanLyDiemSinhVienHAUI.Main;
import QuanLyDiemSinhVienHAUI.Xem.sinhvien;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Tuan Bao
 */
public class Dangnhap extends javax.swing.JFrame {

    /**
     * Creates new form Dangnhap
     */ConnectionDerby db= new ConnectionDerby();
     private taikhoan taikhoan = new taikhoan();
     public static String tkk;
     public static String tkmasv;
     public static String quyentruycap;
     public void settkk(String taikhoan){
         this.tkk=taikhoan;
     }
     public void setmasv(String taikhoan){
         this.tkmasv=taikhoan;
     }
     public void setquyentruycap(String taikhoan){
         this.quyentruycap=taikhoan;
     }
    public Dangnhap() {
        initComponents();
        pldangnhap.setVisible(false);
        
    }
    private taikhoan getThiSinhDetail() {
        String taikhoan = txttaikhoan.getText().trim();
        String matkhau = jpwmatkhau.getText().trim();
        return new taikhoan(taikhoan,matkhau,"SinhVien",null,null,null,null,null);
    }
    public static taikhoan getTaiKhoanObject(ResultSet rs){
        taikhoan item = new taikhoan();
        
        try {
            if(rs.next()){
                item.setTentaikhoan(rs.getString(1));
                item.setMatkhau(rs.getString(2));
                item.setQuyentruycap(rs.getString(3));
                item.setMasv(rs.getString(4));
            }else{
                item = null;
            }
        } catch (SQLException ex) {
            
        }
        
        return item;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pldangnhap = new javax.swing.JPanel();
        txttaikhoan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btndangnhap = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jpwmatkhau = new javax.swing.JPasswordField();
        cbquyentruycap = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        setLocation(new java.awt.Point(700, 250));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Đăng Nhập");

        jLabel2.setText("Chọn quyền truy câp");

        pldangnhap.setToolTipText("");

        jLabel3.setText("Tài khoản");

        jLabel4.setText("Mật khẩu");

        btndangnhap.setText("Đăng nhập");
        btndangnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndangnhapMouseClicked(evt);
            }
        });

        jButton1.setText("Trở lại");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pldangnhapLayout = new javax.swing.GroupLayout(pldangnhap);
        pldangnhap.setLayout(pldangnhapLayout);
        pldangnhapLayout.setHorizontalGroup(
            pldangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pldangnhapLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pldangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pldangnhapLayout.createSequentialGroup()
                        .addGroup(pldangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pldangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttaikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(jpwmatkhau)))
                    .addGroup(pldangnhapLayout.createSequentialGroup()
                        .addComponent(btndangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        pldangnhapLayout.setVerticalGroup(
            pldangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pldangnhapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pldangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pldangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpwmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pldangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbquyentruycap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SinhVien", "Admin" }));
        cbquyentruycap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbquyentruycapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pldangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbquyentruycap, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbquyentruycap, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(pldangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btndangnhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndangnhapMouseClicked
        // TODO add your handling code here:
        taikhoan tk = getThiSinhDetail();
        try{
            taikhoan dn=new taikhoan();
            dn= getTaiKhoanObject(db.getTaiKhoan(tk));
            if(dn != null)
            {
                String selecteditem =(String) cbquyentruycap.getSelectedItem();
                if(dn.getQuyentruycap().equals(selecteditem)){
                        setmasv(dn.getMasv());
                        setquyentruycap(dn.getQuyentruycap());
                        settkk(txttaikhoan.getText());
                    if(selecteditem.equals("SinhVien"))
                    {
                        sinhvien sv=new sinhvien();
                        sv.setVisible(true);
                        this.setVisible(false); 
                    }
                    else
                    {
                       
                        Main m=new Main();
                        m.setVisible(true);
                        this.setVisible(false); 
                    }
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "tài khoản mật khẩu không chính xác");
                }
            }
            else
            {
                 JOptionPane.showMessageDialog(rootPane, "tài khoản mật khẩu không chính xác");
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "đăng nhập thất bại " + ex.toString());
        }
    }//GEN-LAST:event_btndangnhapMouseClicked

    private void cbquyentruycapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbquyentruycapActionPerformed
        // TODO add your handling code here:
        cbquyentruycap.setVisible(false);
        txttaikhoan.setText("");
        jpwmatkhau.setText("");
        jLabel2.setVisible(false);
        pldangnhap.setVisible(true);
        
    }//GEN-LAST:event_cbquyentruycapActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jLabel2.setVisible(true);
        cbquyentruycap.setVisible(true);
        pldangnhap.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dangnhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndangnhap;
    private javax.swing.JComboBox<String> cbquyentruycap;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jpwmatkhau;
    private javax.swing.JPanel pldangnhap;
    private javax.swing.JTextField txttaikhoan;
    // End of variables declaration//GEN-END:variables
}
