/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyDiemSinhVienHAUI.Diem;

import static QuanLyDiemSinhVienHAUI.Diem.QuanLyketquahoctap.mamonhoc;
import QuanLyDiemSinhVienHAUI.Main;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Tuan Bao
 */
public class QuanLyKetQuaThy extends javax.swing.JFrame {

    ConnectionDerby db = new ConnectionDerby();
    private ArrayList<Ketqua> dskq = new ArrayList<Ketqua>();
    public static Double Diemtb;
    private Ketqua kp = new Ketqua();

    /**
     * Creates new form QuanLyKetQuaThy
     */
    public QuanLyKetQuaThy() {
        initComponents();
        lockTextDetail(false);
        setLocation(450, 50);
        loadTable();
    }

    public void loadTable() {
        jTableKetQuaThy.setModel(new CustomTablethi(hienthi()));
    }

    public ArrayList<Ketqua> hienthi() {
        Ketqua tb = getdiemdetal();
        dskq = getdsv(db.getdiem(tb));

        return dskq;

    }

    private void lockTextDetail(boolean state) {
        txtSoTinChi.setEditable(state);
        txtTenMon.setEditable(state);
        txtHocKy.setEditable(state);
    }

    private Ketqua getketqua(String masinhvien) {
        return new Ketqua(mamonhoc, null, null, null, masinhvien, null, null, null, null, null, null, null, -0.5, -0.5, -0.5, null, null);
    }

    private Ketqua getdiemdetal() {

        return new Ketqua(mamonhoc, null, null, null, null, null, null, null, null, null, null, null, -0.5, -0.5, -0.5, null, null);
    }

    private Ketqua getdiem() {
        String mamon = cbmamon.getSelectedItem().toString();
        String masv = txtMaSinhVien.getText().trim();
        Double diemthy = Double.parseDouble(txtDiemThy.getText().trim());
        return new Ketqua(mamon, null, null, -0.5, masv, null, -0.5, -0.5, -0.5, Diemtb, -0.5, null, diemthy, -0.5, -0.5, null, null);
    }

    public ArrayList<Ketqua> getdsv(ResultSet rs) {
        ArrayList<Ketqua> items = new ArrayList<Ketqua>();

        try {
            while (rs.next()) {
                Ketqua item = new Ketqua();
                item.setMaMon(rs.getString(1));
                item.setTenMon(rs.getString(2));
                item.setSoTinChi(rs.getDouble(3));
                item.setHocKy(rs.getDouble(4));
                item.setMaSinhVien(rs.getString(5));
                item.setHoTen(rs.getString(6));
                item.setDiemTX1(rs.getDouble(7));
                item.setDiemTX2(rs.getDouble(8));
                item.setDiemGiuaKy(rs.getDouble(9));
                item.setDiemTrungBinh(rs.getDouble(10));
                item.setSoTietNghi(rs.getDouble(11));
                item.setDieuKienDuThi(rs.getString(12));
                if (rs.getString(13).equals("0.0")) {

                    item.setDiemthy(null);
                    item.setDiemTongKetDiem10(null);
                    item.setDiemTongketDiem4(null);
                } else {
                    item.setDiemthy(rs.getDouble(13));
                    item.setDiemTongKetDiem10(rs.getDouble(14));
                    item.setDiemTongketDiem4(rs.getDouble(15));
                }
                if (rs.getString(12).equals("Học lại")) {
                    item.setDiemChu("F");
                    item.setXepLoai("Kém");
                } else {
                    item.setDiemChu(rs.getString(16));
                    item.setXepLoai(rs.getString(17));
                }

                items.add(item);
                txtSoTinChi.setText(rs.getString(3));
                txtTenMon.setText(rs.getString(2));
                txtHocKy.setText(rs.getString(4));
                Diemtb = rs.getDouble(10);

            }

        } catch (SQLException ex) {

        }
        return items;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenMon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoTinChi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHocKy = new javax.swing.JTextField();
        cbmamon = new javax.swing.JComboBox<String>();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtMaSinhVien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDiemThy = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdiemtb = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKetQuaThy = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnNhapDiem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnSuaDiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý kết quả thi");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Quản lý kết quả thi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chọn mã môn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtTenMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenMonActionPerformed(evt);
            }
        });

        jLabel4.setText("Số tín chỉ");

        jLabel3.setText("Tên môn");

        jLabel5.setText("Mã môn");

        jLabel7.setText("Học Kỳ");

        cbmamon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M01", "M02", "M03", "M04", "M05", "M06", "M07", "M08", "M09", "M10", "M11" }));
        cbmamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmamonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbmamon, 0, 90, Short.MAX_VALUE)
                            .addComponent(txtTenMon))))
                .addGap(91, 91, 91)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 611, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtSoTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(cbmamon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập mã sinh viên và điểm thi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel6.setText("Mã sinh viên");

        txtMaSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSinhVienActionPerformed(evt);
            }
        });

        jLabel8.setText("Điểm thi");

        jLabel9.setText("Điểm Trung bình");

        txtdiemtb.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel8)
                .addGap(36, 36, 36)
                .addComponent(txtDiemThy, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtdiemtb, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemThy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtdiemtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTableKetQuaThy.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableKetQuaThy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableKetQuaThy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKetQuaThyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableKetQuaThy);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290))
        );

        btnNhapDiem.setText("Nhập điểm");
        btnNhapDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhapDiemMouseClicked(evt);
            }
        });
        btnNhapDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapDiemActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });

        btnSuaDiem.setText("Sửa Điểm");
        btnSuaDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaDiemMouseClicked(evt);
            }
        });
        btnSuaDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(btnNhapDiem)
                .addGap(86, 86, 86)
                .addComponent(btnSuaDiem)
                .addGap(78, 78, 78)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNhapDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSuaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenMonActionPerformed

    private void txtMaSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSinhVienActionPerformed
        // TODO add your handling code here:

        Ketqua tb = getketqua(txtMaSinhVien.getText().trim());
        dskq = getdsv(db.getdiemthy(tb));
        txtdiemtb.setText(String.valueOf(Diemtb));


    }//GEN-LAST:event_txtMaSinhVienActionPerformed

    private void jTableKetQuaThyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKetQuaThyMouseClicked
        // TODO add your handling code here:

        int row = jTableKetQuaThy.getSelectedRow();
//        //thí sinh trên dòng chọn chính là bản ghi tứ i trong dsts
        txtMaSinhVien.setText(jTableKetQuaThy.getValueAt(row, 0).toString());

        txtDiemThy.setText(jTableKetQuaThy.getValueAt(row, 2).toString());


    }//GEN-LAST:event_jTableKetQuaThyMouseClicked

    private void cbmamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmamonActionPerformed
        // TODO add your handling code here:
        mamonhoc = cbmamon.getSelectedItem().toString();
        loadTable();
    }//GEN-LAST:event_cbmamonActionPerformed

    private void btnNhapDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapDiemMouseClicked
        Pattern pt = Pattern.compile(kp.getMaSinhVien());
        Matcher m = pt.matcher(txtMaSinhVien.getText().trim());

        try {
            if (txtMaSinhVien.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Mã sinh viên không được để trống!");
                return;
            }
            if (!m.find()) {
                JOptionPane.showMessageDialog(rootPane, "Mã sinh viên bắt đầu bằng SV và theo sau 2 số!");
                return;
            }
            if (txtDiemThy.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Điểm thi không dược để trống!");
                return;
            }
            
            double diemthi = Double.parseDouble(txtDiemThy.getText());

            if (diemthi < 0 || diemthi > 10) {
                JOptionPane.showMessageDialog(rootPane, "Điểm thi phai trong khoảng tư 0 đến 10!");
                return;
            }
            try {
                Ketqua kq = getdiem();
                boolean tb = db.updatediemthi(kq);
                if (tb) {
                    JOptionPane.showMessageDialog(rootPane, "Thông báo thành công");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Thông báo không thành công");
                }
                loadTable();

            } catch (HeadlessException ex) {
                System.out.println("lỗi = " + ex.toString());
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Điểm thi phải là số!");
            return;
        }
    }//GEN-LAST:event_btnNhapDiemMouseClicked

    private void btnNhapDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapDiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhapDiemActionPerformed

    private void btnSuaDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaDiemMouseClicked
        Pattern pt = Pattern.compile(kp.getMaSinhVien());
        Matcher m = pt.matcher(txtMaSinhVien.getText().trim());

        try {
            if (txtMaSinhVien.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Mã sinh viên không được để trống!");
                return;
            }
            if (!m.find()) {
                JOptionPane.showMessageDialog(rootPane, "Mã sinh viên bắt đầu bằng SV và theo sau 2 số!");
                return;
            }
            if (txtDiemThy.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Điểm thi không dược để trống!");
                return;
            }
            
            double diemthi = Double.parseDouble(txtDiemThy.getText());

            if (diemthi < 0 || diemthi > 10) {
                JOptionPane.showMessageDialog(rootPane, "Điểm thi phai trong khoảng tư 0 đến 10!");
                return;
            }
            try {
                Ketqua kq = getdiem();
                boolean tb = db.updatediemthi(kq);
                if (tb) {
                    JOptionPane.showMessageDialog(rootPane, "Thông báo thành công");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Thông báo không thành công");
                }
                loadTable();

            } catch (HeadlessException ex) {
                System.out.println("lỗi = " + ex.toString());
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Điểm thi phải là số!");
            return;
        }
    }//GEN-LAST:event_btnSuaDiemMouseClicked

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatMouseClicked

    private void btnSuaDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaDiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKetQuaThy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKetQuaThy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKetQuaThy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKetQuaThy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyKetQuaThy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhapDiem;
    private javax.swing.JButton btnSuaDiem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cbmamon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKetQuaThy;
    private javax.swing.JTextField txtDiemThy;
    private javax.swing.JTextField txtHocKy;
    private javax.swing.JTextField txtMaSinhVien;
    private javax.swing.JTextField txtSoTinChi;
    private javax.swing.JTextField txtTenMon;
    private javax.swing.JTextField txtdiemtb;
    // End of variables declaration//GEN-END:variables
}
