/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyDiemSinhVienHAUI.Diem;

import QuanLyDiemSinhVienHAUI.Main;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Tuan Bao
 */
public class QuanLyketquahoctap extends javax.swing.JFrame {

    ConnectionDerby db = new ConnectionDerby();
    private ArrayList<Ketqua> dskq = new ArrayList<Ketqua>();
    private Ketqua kp = new Ketqua();
    public static String mamonhoc;

    /**
     * Creates new form QuanLyketquahoctap
     */
    public QuanLyketquahoctap() {
        initComponents();
        setLocation(500, 50);
        lockTextDetail(false);
    }

    public void loadTable() {
        jTableKetQuaHocTap.setModel(new CustomTable(hienthi()));
    }

    public ArrayList<Ketqua> hienthi() {
        Ketqua tb = getdiemdetal();
        dskq = getdsv(db.getdiem(tb));

        return dskq;

    }

    private Ketqua getketqua(String masinhvien) {
        return new Ketqua(mamonhoc, null, null, null, masinhvien, null, null, null, null, null, null, null, 0.0, 0.5, 0.0, null, null);
    }

    private Ketqua getdiemdetal() {

        return new Ketqua(mamonhoc, null, null, null, null, null, null, null, null, null, null, null, -0.5, -0.5, -0.5, null, null);
    }

    private Ketqua getdiem() {
        String masinhvien = txtMaSinhVien.getText().trim();
        String mamon = cbmamon.getSelectedItem().toString();
        Double hocky = Double.parseDouble(txtHocKy.getText().trim());
        Double diemtx1 = Double.parseDouble(txtDiemTX1.getText().trim());
        Double diemtx2 = Double.parseDouble(txtDiemTX2.getText().trim());
        Double Diemgiuaky = Double.parseDouble(txtDiemGiuaKy.getText().trim());
        Double DiemTB = (double) Math.round(((diemtx1 + diemtx2 + Diemgiuaky * 2) / 4) * 10) / 10;
        Double sotietnghi = Double.parseDouble(txtSotietNghi.getText().trim());
        String DieuKienduthi = cbdieukienduthi.getSelectedItem().toString();
        return new Ketqua(mamon, null, null, hocky, masinhvien, null, diemtx1, diemtx2, Diemgiuaky, DiemTB, sotietnghi, DieuKienduthi, 0.0, 0.0, 0.0, null, null);
    }

    public ArrayList<Ketqua> getdsv(ResultSet rs) {
        ArrayList<Ketqua> items = new ArrayList<Ketqua>();

        try {
            while (rs.next()) {
                Ketqua item = new Ketqua();
                item.setMaMon(rs.getString(1));
                item.setTenMon(rs.getString(2));
                item.setSoTinChi(rs.getDouble(3));
                item.setHocKy(rs.getDouble(4));
                item.setMaSinhVien(rs.getString(5));
                item.setHoTen(rs.getString(6));
                item.setDiemTX1(rs.getDouble(7));
                item.setDiemTX2(rs.getDouble(8));
                item.setDiemGiuaKy(rs.getDouble(9));
                item.setDiemTrungBinh(rs.getDouble(10));
                item.setSoTietNghi(rs.getDouble(11));
                item.setDieuKienDuThi(rs.getString(12));
                item.setDiemthy(rs.getDouble(13));
                item.setDiemTongKetDiem10(rs.getDouble(14));
                item.setDiemTongketDiem4(rs.getDouble(15));
                item.setDiemChu(rs.getString(16));
                item.setXepLoai(rs.getString(17));
                items.add(item);
                txtSoTinChi.setText(rs.getString(3));
                txtTenMon.setText(rs.getString(2));
                txtHocKy.setText(rs.getString(4));
            }

        } catch (SQLException ex) {

        }
        return items;
    }

    private void lockTextDetail(boolean state) {
        txtSoTinChi.setEditable(state);
        txtTenMon.setEditable(state);
        txtHocKy.setEditable(state);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenMon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoTinChi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHocKy = new javax.swing.JTextField();
        cbmamon = new javax.swing.JComboBox<String>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtMaSinhVien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDiemTX1 = new javax.swing.JTextField();
        txtDiemTX2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDiemGiuaKy = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSotietNghi = new javax.swing.JTextField();
        cbdieukienduthi = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKetQuaHocTap = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý kết quả học tập");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chọn mã môn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setToolTipText("");

        txtTenMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenMonActionPerformed(evt);
            }
        });

        jLabel4.setText("Số tín chỉ");

        jLabel3.setText("Tên môn");

        jLabel2.setText("Mã môn");

        jLabel7.setText("Học Kỳ");

        cbmamon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M01", "M02", "M03", "M04", "M05", "M06", "M07", "M08", "M09", "M10", "M11" }));
        cbmamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmamonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenMon)
                    .addComponent(cbmamon, 0, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 550, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtSoTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(cbmamon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel6.setText("Mã sinh viên");

        txtMaSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSinhVienActionPerformed(evt);
            }
        });

        jLabel8.setText("Điểm TX1");

        jLabel9.setText("Điểm TX2");

        jLabel11.setText("Điểm giữa kỳ");

        jLabel12.setText("Số tiết nghỉ");

        jLabel13.setText("Điều kiện dự thi");

        txtSotietNghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSotietNghiActionPerformed(evt);
            }
        });

        cbdieukienduthi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Đủ điều kiện", "Học lại", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(txtDiemTX1))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDiemGiuaKy, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(txtDiemTX2))
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSotietNghi)
                    .addComponent(cbdieukienduthi, 0, 92, Short.MAX_VALUE))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtDiemTX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtSotietNghi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel8)
                    .addComponent(txtDiemTX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtDiemGiuaKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbdieukienduthi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Quản lý kết quả học tập");

        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTableKetQuaHocTap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableKetQuaHocTap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKetQuaHocTapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableKetQuaHocTap);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenMonActionPerformed

    private void txtMaSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSinhVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSinhVienActionPerformed

    private void txtSotietNghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSotietNghiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSotietNghiActionPerformed

    private void cbmamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmamonActionPerformed
        // TODO add your handling code here:
        mamonhoc = cbmamon.getSelectedItem().toString();
        loadTable();
    }//GEN-LAST:event_cbmamonActionPerformed

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked

        Pattern pt = Pattern.compile(kp.getMaSinhVien());
        Matcher m = pt.matcher(txtMaSinhVien.getText().trim());

        try {
            if (txtMaSinhVien.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Mã sinh viên không được để trống!");
                return;
            }
            if (!m.find()) {
                JOptionPane.showMessageDialog(rootPane, "Mã sinh viên bắt đầu bằng SV và theo sau 2 số!");
                return;
            }
            if (txtDiemTX1.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Điểm TX1 không dược để trống!");
                return;
            }
            if (txtDiemTX2.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Điểm TX2 không dược để trống!");
                return;
            }
            if (txtDiemGiuaKy.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Điểm giữa kỳ không dược để trống!");
                return;
            }
            if (txtSotietNghi.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Số tiết nghỉ không được để trống!");
                return;
            }
            double diemTX1 = Double.parseDouble(txtDiemTX1.getText());
            double diemTX2 = Double.parseDouble(txtDiemTX2.getText());
            double diemgiuaky = Double.parseDouble(txtDiemGiuaKy.getText());
            double sotietnghi = Double.parseDouble(txtSotietNghi.getText());
            if (diemTX1 < 0 || diemTX1 > 10) {
                JOptionPane.showMessageDialog(rootPane, "Điểm TX2 phai trong khoảng tư 0 đến 10!");
                return;
            }
            if (diemTX2 < 0 || diemTX2 > 10) {
                JOptionPane.showMessageDialog(rootPane, "Điểm TX2 phai trong khoảng tư 0 đến 10!");
                return;
            }
            if (diemgiuaky < 0 || diemgiuaky > 10) {
                JOptionPane.showMessageDialog(rootPane, "Điểm Giữa kỳ phai trong khoảng tư 0 đến 10!");
                return;
            }

            if (sotietnghi < 0) {
                JOptionPane.showMessageDialog(rootPane, "Số tiết nghi phai lớn hơn hoặc bằng 0!");
                return;
            }
            try {
                Ketqua kq = getdiem();
                boolean tb = db.add(kq);
                if (tb) {
                    JOptionPane.showMessageDialog(rootPane, "Thông báo thành công");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Thông báo không thành công");
                }
                loadTable();

            } catch (HeadlessException ex) {
                System.out.println("lỗi = " + ex.toString());
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Phải điểm và số tiết nghỉ là số!");
            return;
        }
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        Pattern pt = Pattern.compile(kp.getMaSinhVien());
        Matcher m = pt.matcher(txtMaSinhVien.getText().trim());

        try {
            if (txtMaSinhVien.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Mã sinh viên không được để trống!");
                return;
            }
            if (!m.find()) {
                JOptionPane.showMessageDialog(rootPane, "Mã sinh viên bắt đầu bằng SV và theo sau 2 số!");
                return;
            }
            if (txtDiemTX1.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Điểm TX1 không dược để trống!");
                return;
            }
            if (txtDiemTX2.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Điểm TX2 không dược để trống!");
                return;
            }
            if (txtDiemGiuaKy.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Điểm giữa kỳ không dược để trống!");
                return;
            }
            if (txtSotietNghi.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Số tiết nghỉ không được để trống!");
                return;
            }
            double diemTX1 = Double.parseDouble(txtDiemTX1.getText());
            double diemTX2 = Double.parseDouble(txtDiemTX2.getText());
            double diemgiuaky = Double.parseDouble(txtDiemGiuaKy.getText());
            double sotietnghi = Double.parseDouble(txtSotietNghi.getText());
            if (diemTX1 < 0 || diemTX1 > 10) {
                JOptionPane.showMessageDialog(rootPane, "Điểm TX2 phai trong khoảng tư 0 đến 10!");
                return;
            }
            if (diemTX2 < 0 || diemTX2 > 10) {
                JOptionPane.showMessageDialog(rootPane, "Điểm TX2 phai trong khoảng tư 0 đến 10!");
                return;
            }
            if (diemgiuaky < 0 || diemgiuaky > 10) {
                JOptionPane.showMessageDialog(rootPane, "Điểm Giữa kỳ phai trong khoảng tư 0 đến 10!");
                return;
            }

            if (sotietnghi < 0) {
                JOptionPane.showMessageDialog(rootPane, "Số tiết nghi phai lớn hơn hoặc bằng 0!");
                return;
            }
            try {
                Ketqua kq = getdiem();
                boolean tb = db.update(kq);
                if (tb) {
                    JOptionPane.showMessageDialog(rootPane, "Thông báo thành công");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Thông báo không thành công");
                }
                loadTable();

            } catch (HeadlessException ex) {
                System.out.println("lỗi = " + ex.toString());
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Phải điểm và số tiết nghỉ là số!");
            return;
        }
    }//GEN-LAST:event_btnSuaMouseClicked

    private void jTableKetQuaHocTapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKetQuaHocTapMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        int row = jTableKetQuaHocTap.getSelectedRow();
//        //thí sinh trên dòng chọn chính là bản ghi tứ i trong dsts
        txtMaSinhVien.setText(jTableKetQuaHocTap.getValueAt(row, 0).toString());
        txtDiemTX1.setText(jTableKetQuaHocTap.getValueAt(row, 2).toString());
        txtDiemTX2.setText(jTableKetQuaHocTap.getValueAt(row, 3).toString());
        txtDiemGiuaKy.setText(jTableKetQuaHocTap.getValueAt(row, 4).toString());
        txtSotietNghi.setText(jTableKetQuaHocTap.getValueAt(row, 6).toString());
        cbdieukienduthi.setSelectedItem(jTableKetQuaHocTap.getValueAt(row, 7).toString());
//        // gan du lieu cho cac o text tương ứng dòng chọn
//        setTextDetail(kq);
    }//GEN-LAST:event_jTableKetQuaHocTapMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        try {
            if (txtMaSinhVien.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Mã sinh viên không được để trống!");
                return;
            }
            int click = JOptionPane.showConfirmDialog(null, "Chắc xóa điểm này", "Xóa?", JOptionPane.YES_NO_OPTION);
            if (click == JOptionPane.YES_OPTION) {
                //lấy dòng chọn hiện thời trong table
                int row = jTableKetQuaHocTap.getSelectedRow();
                //lấy số báo danh ở cột 0
                String masinhvien = jTableKetQuaHocTap.getValueAt(row, 0).toString();
                //truyền vào phognf thi xóa theo sbd
                Ketqua newkq = getketqua(masinhvien);
                db.delete(newkq);
                loadTable();

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không xóa được " + ex.toString());
        }
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyketquahoctap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyketquahoctap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyketquahoctap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyketquahoctap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyketquahoctap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbdieukienduthi;
    private javax.swing.JComboBox<String> cbmamon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKetQuaHocTap;
    private javax.swing.JTextField txtDiemGiuaKy;
    private javax.swing.JTextField txtDiemTX1;
    private javax.swing.JTextField txtDiemTX2;
    private javax.swing.JTextField txtHocKy;
    private javax.swing.JTextField txtMaSinhVien;
    private javax.swing.JTextField txtSoTinChi;
    private javax.swing.JTextField txtSotietNghi;
    private javax.swing.JTextField txtTenMon;
    // End of variables declaration//GEN-END:variables
}
